package com.aleslul.biblioteca.model.enums;

public enum TipoAccion {
    REPORTE_CIRCULACION,
    REPORTE_LIBROS_SOLICITADOS,
    REPORTE_ESTADISTICAS,
    NOTIFICACION_VENCIMIENTO,
    NOTIFICACION_LIBRO_DISPONIBLE,
    NOTIFICACION_MULTA_APLICADA,
    RENOVACION_PRESTAMO,
    REGISTRO_PRESTAMO
}